import { type NextPage } from "next";
import Head from "next/head";

import React from "react";
import ContactForm from "~/components/ContactForm";
import Experience from "~/components/Experience";
import Intro from "~/components/Intro";
import Portfolio from "~/components/Portfolio";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Grays Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/coding-icon.svg" />
      </Head>
      <main className="App overflow-hidden bg-gradient-to-b from-blue-100 to-yellow-100">
        <Navbar />
        <Intro />
        <Portfolio />
        <Experience />
        <ContactForm />
      </main>
    </>
  );
};

export default Home;
